Adds Notifications section to README
ChromaticHQ/site-launch-guide pull request #1
Opened 2018-08-29 10:41 UTC by ctorgalson

- Also adds Update Status item to basic list.

2018-08-29 13:24 UTC, chrisfree requested changes

2018-08-29 13:24 UTC, chrisfree commented on README.md
> +* Is the [Security Review](https://www.drupal.org/project/security_review) module installed and providing a clean report?
Looks like there isn't an official release for this module on D8?

2018-08-29 13:24 UTC, chrisfree commented on README.md
> +* Sites using HTTPS that *do not use Letsencrypt* should have a Jenkins job configured send weekly messages about upcoming certificate renewal dates to a Slack channel (preferably one that the client
Should this be 
> do not use _Let's Encrypt_ should have a Jenkins job _to_ configured

2018-08-30 08:11 UTC, ctorgalson commented on README.md
> +* Is the [Security Review](https://www.drupal.org/project/security_review) module installed and providing a clean report?
It's been shipping in core since D6. We just have to turn it on.

2018-08-30 08:14 UTC, ctorgalson commented on README.md
> +* Sites using HTTPS that *do not use Letsencrypt* should have a Jenkins job configured send weekly messages about upcoming certificate renewal dates to a Slack channel (preferably one that the client
Fixed by 87bed6a.

2018-08-30 12:19 UTC, chrisfree commented on README.md
> +* Is the [Security Review](https://www.drupal.org/project/security_review) module installed and providing a clean report?
@ctorgalson sorry, I'm talking about the `security_review` module. I realize now that you aren't changing that line at all.

2018-08-30 12:19 UTC, chrisfree approved these changes

2018-08-30 12:38 UTC, ctorgalson commented on README.md
> +* Is the [Security Review](https://www.drupal.org/project/security_review) module installed and providing a clean report?
Ah! I Get it now.

2018-08-30 12:38 UTC, merged